preprocess:
  data_directory: 'datasets/'
  cache_file: true
  shuffle: true
  batch_size: 100
  is_normalized: true
  smoothing_windows:
    - 20
    - 100
    - 200
  downsamples:
    - 2
    - 4
  drop_labels:
    - 91
    - 92
    - 99
  max_length_ts: 200