preprocess:
  data_directory: 'datasets/'
  test_directory: 'datasets/test/'
  val_directory: 'datasets/validation'
  cache_file: true
  shuffle: true
  batch_size: 20
  is_normalized: true
  train_size: 0.80
  test_size: 0.15
  val_size: 0.05
  smoothing_windows:
    - 20
    - 75
    - 200
  downsamples:
    - 2
    - 4
  drop_labels:
    - 91
    - 92
    - 99
    - 0
  max_length_ts: 215
  channels: 22

convolutions_conf:
  conv1:
    filters: 4
    kernel_size: 5
    activation: 'relu'
  conv2:
    filters: 4
    kernel_size: 5
    activation: 'relu'

dense_conf:
  flatten_dropout:
    dropout: 0.5
  dense1:
    units: 128
    activation: relu
  dropout1:
    dropout: 0.3
  dense2:
    units: 64
    activation: relu
  output:
    units: 7
    activation: softmax
